version: "3.9"


services:
  mysql:
      image: mysql:8.0
      container_name: mysql
      environment:
        - MYSQL_ROOT_PASSWORD=YourPassword123
        - MYSQL_DATABASE=TamaraResDB
        - MYSQL_USER=tamara
        - MYSQL_PASSWORD=tamara123
      ports:
        - "3307:3306"
      volumes:
        - tamara_data:/var/lib/mysql
        - ./db.sql:/docker-entrypoint-initdb.d/init.sql:ro
      restart: always

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT=5000
      - NODE_ENV=development
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=tamara
      - MYSQL_PASSWORD=tamara123
      - MYSQL_DATABASE=TamaraResDB
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    restart: always
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    stdin_open: true
    tty: true  
    environment:
      - PORT_SERVER=5000
      - PORT_FRONTEND=3000  
    ports:
      - "3000:3000"
    restart: always
volumes:
  tamara_data: